### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by hadim** [flying-sheep/revealjs-template#1]
Yeah I found how it works now but it tooks some time !!!

For next users, I advise you to add some instructions to the README file.

**Comment by flying-sheep** [comment]
you mean installation/usage instructions? gladly!

can you tell me what was especially hard to do?

**Comment by hadim** [comment]
Well nothing hard to do. It wasn't obvious what to do to make it works.

```
$ # Install deps
$ npm install
$ # Launch the dev server
$ gulp
```

Something like that.

**Comment by flying-sheep** [comment]
sure, will do in a second!
